### ISSUE TITLE
Add refresh on arrival details page and last known location map page

### ISSUE THREAD

**Issue by RobBednark** [teleportaloo/PDX-Bus#17]
I **love** the PDX Bus app!  Thanks @teleportaloo!

Here's a scenario I do many times every day:
1. go to a stop (e.g., SW 5th & Pine)
2. click on a particular bus arrival (e.g., 44 to PCC Sylvania scheduled 4:58pm)
3. on the "Details" page, look at the "Last known location" so I know where the bus is now
4. several minutes later, go back to steps 2 and 3 so that I can refresh the info to see how close the bus is now

It would be great to have a refresh ability on the "Details" page so I don't have to go back to refresh.  It would also be nice to have a refresh option on the last known location map page that shows where the bus is.

**Comment by PolarisBeaver** [comment]
I agree, please add this @teleportaloo !

**Comment by teleportaloo** [comment]
This is in the next release... :-)

**Comment by PolarisBeaver** [comment]
Great ;)

**Comment by teleportaloo** [comment]
Fixed ages ago.
