### ISSUE TITLE
IPad travel planner doesn't show date time arrival options

### ISSUE THREAD

**Issue by deboots** [teleportaloo/PDX-Bus#18]
i was trying to use the trip planner on my iPad but when I try to select the 'arrive by' option the area where I would select the date and time is blank.   I just downloaded this to my iPad.  I use this on my phone all the time. (Thank you!).  I believe my iPad is iOS 8 now.

**Comment by teleportaloo** [comment]
Known issue will be fixed in next release;  it is an issue with the rotation of the iPad, if you rotate it the other way it will work.

**Comment by teleportaloo** [comment]
Fixed in 7.9
