### ISSUE TITLE
Alarms arn't working on a recent install

### ISSUE THREAD

**Issue by bcomnes** [teleportaloo/PDX-Bus#27]
After getting a new phone and reinstalling the app (not restoring a backup), it seems the arrival alarm is no longer working.

Not sure if its related, but the app never asked for permissions to perform background activity, or is it listed as an app that you can enable or disable for backgrounding permission.

Running: Latest version of the app (as of today and the latest iOS on an iphone 5s)

**Comment by teleportaloo** [comment]
It's a known problem; fixed in the next release.  For this feature the app does not ask for background activity, but it needed to ask for additional permissions for notifications.

**Comment by bcomnes** [comment]
Sounds good.  Should I leave this open till the release?

**Comment by bcomnes** [comment]
Working on the new update. Love it!

**Comment by teleportaloo** [comment]
Phew!
