### ISSUE TITLE
Using address from contacts causes app crash

### ISSUE THREAD

**Issue by teachthom** [teleportaloo/PDX-Bus#28]
When I'm doing a trip plan, if I need to select an address from my contacts as the starting point, the app crashes. 

I've got iOS 10 running the latest version of your app. 

Thanks for all the hard work that goes into maintaining this critical tool for me :) I'm a driver for TriMet who suggests this app to everyone!

**Comment by teleportaloo** [comment]
Thanks, I have fixed it in the next release!
