### ISSUE TITLE
Trip planner isn't always showing bus departure times

### ISSUE THREAD

**Issue by marijane** [teleportaloo/PDX-Bus#29]
Environment:
iOS 10.3.2
PDX Bus 9.1.0

Problem:
Sometime in the last week or so, I have observed the trip planner fail to indicate departure times for trips.  Instead of listing, say "Bus 15 9:38AM" it instead says "Bus TriMet:15".  This is basically rendering the trip planner useless because it's not telling me when I need to leave to catch the bus!  I know the app hasn't updated in a while so I'm guessing TriMet may have changed something in their API?

**Comment by teleportaloo** [comment]
I've sent an email to TriMet - I can see that the response from the server sometimes has TriMet: in front of it - this is new!

**Comment by teleportaloo** [comment]
(Sorry for the delay - was on vacation)

**Comment by marijane** [comment]
No worries, thank you for the response!

**Comment by teleportaloo** [comment]
TriMet got back to me and it has now been fixed - new trips will no longer insert the TriMet: into a response (this does not require an app update - it was fixed on the server).
