### ISSUE TITLE
App Icon Issue with iOS 11 animations (and a solution!)

### ISSUE THREAD

**Issue by PolarisBeaver** [teleportaloo/PDX-Bus#31]
iOS 11 has a new animation for launching and closing applications. It involves "stretching" the icon to expand to the screen. It uses the bordering colors to automatically fill in the surrounding exposed area it as it expands and contracts.

Here is a GIF of the animation in action:
![pdxbusanimation](https://user-images.githubusercontent.com/10394552/32921992-ef899c4c-cae4-11e7-8f54-e8b8ba9cd9be.gif)

Here is a still from the gif so you can see it more clearly:
![pdxbusstatic](https://user-images.githubusercontent.com/10394552/32922010-0716e324-cae5-11e7-9933-f7aee17c1271.jpg)

The issue is most obvious on iPhone X, however it is still seen (albeit minimally) on other iPhones, such as the iPhone 5s I used to compare, as seen here:
![pdxbusstatic2](https://user-images.githubusercontent.com/10394552/32922051-38f24dca-cae5-11e7-89fd-5219c8ba065e.jpg)

The solution to this is simple. Take the existing icon assets, and remove the (now dated) shadow border layer from the icon. This app requires iOS 8.0 or later, therefore the icon shadow from the iOS 6 era is no longer a necessity. It was fine before since nobody could see it, however iOS 11 has exposed this issue on a daily basis as the app is launched and closed.

Here I have created a quick mockup showing how the problem can be fixed, and very easily. Please note how the color is solid even on the very last pixels on the edges of the icon.

![compare](https://user-images.githubusercontent.com/10394552/32922311-6fe5cf22-cae6-11e7-88be-86f94fe06850.png)

**Comment by teleportaloo** [comment]
Thanks!

I think actually the old one above is not one that will cause the worst problem.  

Some of the old ones actually do not have the corners filled in with color, others did have the corners filled in. The iPhone 5S icon has colored corners but the 3x one for the iPhone X has black corners.  :-( .    I have tried to replace all the icons with one that looks like the old one, but there is still a slight problem at the bottom with the edge being black in the middle.

The icon is in fact shaded in a sophisticated way - I will try to see if the original designer is willing to provide me with a new one without the border.

**Comment by teleportaloo** [comment]
Didn't mean to close this.  Duh. Still working on it. :-)

**Comment by PolarisBeaver** [comment]
I'm glad you're looking into this! And i'm not sure if I misunderstood, but when you say "the edge being black in the middle", are you talking about the door split? Here's a hastily edited mockup edit showing what it may look like! This may not look "perfect", for instance the yellow part of the design is not symmetrical with the top blue area BUT it definitely looks better than how it looks right now with all that black showing. It would be much less noticeable. And it would still look like train doors!

![pdxbusstaticfixed](https://user-images.githubusercontent.com/10394552/33011752-bc1622f2-cd93-11e7-91fa-f03017131ee7.jpg)

**Comment by teleportaloo** [comment]
This was fixed as now I use icons just like you suggested!
