### ISSUE TITLE
Delayed bus color (Brown) contrast

### ISSUE THREAD

**Issue by PolarisBeaver** [teleportaloo/PDX-Bus#32]
I like how you have color coded delayed busses, however the color contrast between the gray scheduled times and brown delayed times is so similar, it is hard to tell. I’m not even colorblind but I find it hard to tell the difference unless I look at it more closely. Actual color blind users would find the difference impossible to see. May I suggest a more vivid brown or tan color perhaps? Here’s a screenshot of the delayed busses next to scheduled busses.

![4323b06c-6e92-4c31-9c25-2a90495e1add](https://user-images.githubusercontent.com/10394552/36058201-55511898-0dcf-11e8-95cf-60ec85706cc9.png)

**Comment by teleportaloo** [comment]
This was fixed;  I use magenta for late items now,
